# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Run Unittests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.3]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test env vars for python
        run: python -c 'import os;print(os.environ)'
        env:
          SECRET_TEST: ${{ secrets.SECRET_TEST }}

        #python -m unittest hello_world1.tests.test_functions
        #python -m unittest hello_world2.tests.test_functions
      - name: Test inline env vars for python
        run: SECRET_TEST=${{ secrets.SECRET_TEST }} python -c 'import os;print(os.environ)'

      - name: Test multiline env vars for python
        run: |
          SECRET_TEST=${{ secrets.SECRET_TEST }} 
          python -c 'import os;print(os.environ)'
